#ifndef MORTAR_BINDING_HELPERS_HLSLI
#define MORTAR_BINDING_HELPERS_HLSLI

#if defined(SPIRV) || defined(TARGET_VULKAN)
#define MORTAR_PUSH_CONSTANT [[vk::push_constant]]
#else
#define MORTAR_PUSH_CONSTANT
#endif

#define MORTAR_REGISTER_HELPER(TYPE, SLOT, SPACE) register(TYPE##SLOT, space##SPACE)
#define MORTAR_CBUFFER(SLOT, SPACE) MORTAR_REGISTER_HELPER(b, SLOT, SPACE)
#define MORTAR_SRV(SLOT, SPACE) MORTAR_REGISTER_HELPER(t, SLOT, SPACE)
#define MORTAR_SAMPLER(SLOT, SPACE) MORTAR_REGISTER_HELPER(s, SLOT, SPACE)
#define MORTAR_PUSH_CONSTANTS(TYPE, NAME, SLOT, SPACE) \
    MORTAR_PUSH_CONSTANT ConstantBuffer<TYPE> NAME : MORTAR_CBUFFER(SLOT, SPACE)

#endif
